background            #000000
foreground            #6e6e6e
cursor                #fcee0b


color0                    #000000
color1                    #ed333b
color2                    #57e389
color3                    #ff7800
color4                    #62a0ea
color5                    #9141ac
color6                    #5bc8af
color7                    #deddda

color8                    #9a9996
color9                    #f66151
color10                   #8ff0a4
color11                   #ffa348
color12                   #99c1f1
color13                   #dc8add
color14                   #93ddc2
color15                   #f6f5f4

#  color0                #1b1d1e
#  color8                #535050
#  color1                #e8dd4a
#  color9                #fff480
#  color2                #cac04e
#  color10               #fff280
#  color3                #f1fd1c
#  color11               #feed6c
#  color4                #5a575b
#  color12               #8a8e8f
#  color5                #676665
#  color13               #8b8a8f
#  color6                #5b5957
#  color14               #8a8a8f
#  color7                #c5c5be
#  color15               #dadad5

selection_foreground #FFC436
selection_background #070707

active_tab_foreground   #6c6c6c
active_tab_background   #000000
inactive_tab_foreground #303030
inactive_tab_background #000000
