require("kbgjtn.plugins-setup")
require("kbgjtn.core.options")
require("kbgjtn.core.keymaps")
require("kbgjtn.core.colorscheme")
require("kbgjtn.core.highlights")
require("kbgjtn.plugins.comment")
-- if you want use theme neosolarized
-- require("kbgjtn.plugins.neosolarized")
require("kbgjtn.plugins.nvim-tree")
require("kbgjtn.plugins.lualine")
require("kbgjtn.plugins.telescope")
require("kbgjtn.plugins.nvim-cmp")
require("kbgjtn.plugins.lsp.mason")
require("kbgjtn.plugins.lsp.lspsaga")
require("kbgjtn.plugins.lsp.lspconfig")
require("kbgjtn.plugins.lsp.null-ls")
require("kbgjtn.plugins.autopairs")
require("kbgjtn.plugins.treesitter")
require("kbgjtn.plugins.gitsigns")
